### ISSUE TITLE
bzip2 decompress

### ISSUE THREAD

**Issue by xinjijia** [libyal/assorted#3]
Hello, I have a compressed package produced by modified bzip2. How can I decompress it? Thank you
the file down link   https://we.tl/t-U5VLMnpr16
file is Is an unknown program to modify the bZIP source code, generated by the compressed package

**Comment by joachimmetz** [comment]
@xinjijia why are you asking me? or in this project for that matter?

**Comment by xinjijia** [comment]
Hello, you are an expert in decompression, so I'd like to ask if I can help you analyze this compressed package. If I disturb you, I'm very sorry.




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2021年5月1日(星期六) 凌晨2:52
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [libyal/assorted] bzip2 decompress (#3)






@xinjijia你为什么问我？

—
你收到这个是因为你被提到了。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by joachimmetz** [comment]
Unfortunately I cannot help you

1. I don't know who you are and why you want to be able to decompress this file, for all I know this could be your homework assignment
2. you flatter me, but I'm do not consider myself an [expert](https://en.wikipedia.org/wiki/Expert) in decompression, what I know of decompression is through analyzing documentation and source code available
3. this request is out of scope for this project

Closing issue.
